import type { Metadata } from "next";
import HeaderLogin from "@/components/layout/HeaderLogin";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {    return (
        <html lang="en">
            <body className="bg-gray-700">
                <HeaderLogin/>
                <div className="bg-[url(@/public/herobanner.png)] h-[200px] w-full bg-cover bg-center flex justify-center items-center">
                    <span className="text-3xl text-white">Login</span>
                </div>
                {children}
            </body>
        </html>
    );
}
