import type { Metadata } from "next";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className="bg-[url(@/public/herobanner.png)] h-[200px] w-full bg-cover bg-center"></div>
        {children}
      </body>
    </html>
  );
}
