import type { Metadata } from "next";
import { UserProvider } from "@/contexts/users/userContext"; // Import UserProvider

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {    return (
        <html lang="en">
            <body>
                <UserProvider> {/* Wrap children with UserProvider */}
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
